### ISSUE TITLE
1/12/2023: Marc Berman

### ISSUE THREAD

**Issue by bhavyapan** [uchicago-computation-workshop/Fall2022#10]
This Github Issue page has been moved to https://github.com/uchicago-computation-workshop/Winter2023/issues/1

Apologies for the confusion but the Winter 2023 workshop information will be in the Winter2023 repo from now on. We left this issue page up by accident when transferring to the new repository.

**Comment by secorey** [comment]
Hi Dr. Berman,

Thanks for your presentation. Page 4 of the article mentions that heterophobia and homophily are assumed to be uncorrelated in the model. I am unfamiliar with the literature, but it seems to me that there would be a correlation between an individual's preference for interactions with members of their in-group and avoidance of members of their out-group. Maybe I am misinterpreting the definitions of heterophobia and homophily, but could you clarify this?

Best,
Sam

**Comment by yuzhouw313** [comment]
Hello Dr. Berman,
Thank you for sharing your research with us. I am deeply intrigued by the relation between the trend of residential/neighborhood segregation and economic development in consideration of the Urban Scaling Theory. 

I am not sure if I understand the concept of the representation of the outcome homophily and heterophobia, as you described it as not indicating personal choice but macro-level network segregation (see page 5). However, from a perspective from someone who is not familiar with urban environment related theories, I generally consider the individual preference the foundation of the aggregated level of segregation, and I am not sure I understand the process of calculating these two indicators (hg^hom and hg^het). Can you please elaborate on these two variables/indicators? And how can you build the aggregation form from individual segments?

Thank you again and look forward meeting you at Thursday's workshop for more information on this topic.

**Comment by Sirius2713** [comment]
Hi Professor Berman,

Thanks a lot for sharing your research. I really enjoy reading the racial segregation and economic productivity paper. I especially appreciate this paper provides both theoretical and empirical evidence to validate the hypothesis. My question is about the boundaries of neighborhoods when calculating segregation-related indexes. Are the boundaries defined based on the official district map? I'm asking because when boundaries change, a neighborhood with a high minority concentration might become one with a low minority concentration. For example, people are always referring to Hyde Park as an "island" on the south side of Chicago. Are neighborhoods like Hyde Park included in the same region as Woodlawn or Englewood when calculating the minority concentration? Moreover, during the time range of your research, have the boundaries between different groups ever changed?

**Comment by LynetteDang** [comment]
Hi Dr. Berman,

Thank you for sharing your work with us. Your work lies exactly in the intersection among urban science, neuroscience, and economics, it was so fascinating to see how all these different elements coming into play. Do you think ultimately there will be a solution for the increasing residential racial heterophobia segregation in the near future? I am looking forward to your presentation.

**Comment by zihua-uc** [comment]
Hi Dr. Berman,

I wonder how much of the racial segregation is due to taste-based racial biases and how much is based on statistical discrimination. Some people might avoid certain neighborhoods because they are unsafe, but that could be correlated with the racial composition of the neighborhood. 
Also. what are the policy implications - how could the government "encourage" less racial segregation to increase economic output?

**Comment by pranathiiyer** [comment]
Hi Prof Marc,
Thanks so much for sharing your work with us!
I'm not sure if I missed this in the paper, but how can we account for regional differences in economic opportunities in a model like this. For instance, perhaps certain regions might have different landscapes and opportunities for industries and economic opportunities that might lead to higher GDP or median income. In such cases it might not be the segregation but preexisting nature of the region itself that might show differences in economic output. Did you see any effects of such relationships?

**Comment by AlexPrizzy** [comment]
Hi Marc!
Thanks for sharing this research with the MACSS workshop. I'm wondering what the practical uses of this model can be. How can it be used to design and optimize cities of the future to mitigate the effects of racial segregation and maximize economic output? Can it be used in something like an algorithm for companies to recruit potential employees from targeted areas with the intent of mutual benefit for the company and the employees community?

**Comment by JoeHelbing** [comment]
Professor Berman,

Can you expand a bit  on the difference in levels of economic output. On page 11 where you use the example of New Orleans you present the three figures:
Median Income--$54,400
Urban Scaling Law Expectation--$65,000
Accounting for Segregation--$56,500

Am I correct in understanding your analysis of these figures is that accounting for segregation brings the expected median income down to $56,500 and that negative interaction of Heterophobia plus the compensating positive factor of Homophily combined accounts for the final negative $2,100 difference between the two?

You mention that that the strength of the relationship increase throughout the 2010s, do you mean in reference to its economic effects? Is this in relation to increasing heterophobia or some increase in the economic effect of heterophobia?

Thank you,
Joe

**Comment by kuitaiw** [comment]
Hi Prof. Berman,
Thank you for coming. And I think there might be wrong conclusion that regional differences may cause. This can thus lead to selection bias. Because regional segregation does not necessarily exist at the economic level. It may also be due to economic level segregation caused by regions.

**Comment by ValAlvernUChic** [comment]
Hello Prof Berman, 

Thank you for the paper! I was thinking about the mechanism that makes heterogeneous social interactions associated with economic outcomes. In a country like Singapore, our racial heterogeneity is largely socially engineered, with numerous policies ensuring that population proportions of races are reflected from our neighborhoods to individual apartment blocks. However, it is also known that we have a large proportion of migrant workers from the surrounding countries whose only purpose in the country is to act as labour e.g. domestic workers and construction workers. Whether engineered or not, these communities are usually "separate", both socially and physically, from the general Singaporean population. I wonder how the results in this paper would look applied to this context i.e. is it the case that better integrating these migrant populations in the country would mean better economic outputs?

**Comment by QichangZheng** [comment]
Hello, Dr. Berman

Thank you for letting us see your work. Urban science, neurology, and economics all cross precisely where your work takes place, and it was fascinating to observe how these many factors interacted. Do you anticipate a long-term remedy for the growing residential racial segregation problem in the foreseeable future? I'm excited to hear what you have to say.

**Comment by taizeyu** [comment]
Hi Prof. Berman

It is a wonderful paper. I am curious that what is the following step of the research

**Comment by xin2006** [comment]
Hi Dr. Berman 
Thank you for sharing the work.  Homophily is a topic I am interested in in the social network analysis. There is a tendency that members in a social group would connect with individuals similar with them in some attributes. On the other hand, much connection among people might result in the similarity among them. How do you think about the mutual effect in terms of Homophily?

**Comment by zbchen0129** [comment]
Hi Dr. Berman
Thanks for sharing your good work with us. Your idea trying to analyze the effect of racial segregation, homophily and heterophobia on economic results is impressive. At the same time I have some questions. How do you avoid bias when estimating racial segregation and social interaction since it is hard to know the exact number of them? And when using median income and GDP to measure economic productivity, how do you eliminate the effect of time? Thanks!

**Comment by edelahayeUChicago** [comment]
Hi Prof Berman,

My question is how your work relates to the literatures on urban planning, which is linked to the urban scaling literature. How can we untangle the effect that others factors (such as city age, architectural design, layout, etc) that correlate to the factors you look at (size, diversity, segregation) have outcomes? Given that cities are shaped over decades if not centuries in some cases and this impacts the flavour of a city's culture as both a cause and an effect variable, this likely will be important?

How can your results be used in the optimal planning of cities?

**Comment by xinyi030** [comment]
Hi Prof. Berman, 

Thanks for sharing your work with us. My questions are related to the topic of racial segregation and economic productivity.
- What are some innovative policy solutions that could be implemented to mitigate the negative effects of racial segregation on economic productivity?
- How does racial segregation interact with other forms of inequality, such as class and gender, to shape economic outcomes?
- How has the COVID-19 pandemic and its economic fallout affected racial segregation and economic productivity?

Looking forward to your presentation!

**Comment by mingxuan-he** [comment]
Hi prof. Berman, I'm curious about the effect of community structures in reducing depression in large city networks. Does connection within community serve as a buffer as well?

**Comment by bairr1208** [comment]
Hi Prof. Berman,
Thanks so much for sharing your work. My question is about social interaction. Since neighborhood plays a role in the socio-economic relationship, what do you think about the status of a community in decreasing heterophobia?

**Comment by kunkunz111** [comment]
Hi prof. Berman.
Thanks for your sharing. I am curious whether Covid magnifies racial segregation because people may stay away from each other for health purposes.

**Comment by yunshu3112** [comment]
Hi Prof Berman,

I really enjoyed reading your paper. I am curious about how you think of reverse causality, i.e. the economic output may reversely shape network structure and levels of heterophobia. Thank you!
